# Generated by Django 2.2.2 on 2019-06-15 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=31, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=31, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('short_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('clicks', models.IntegerField()),
                ('rating', models.SmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Stats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_words', models.IntegerField(blank=True, null=True)),
                ('total_sentences', models.IntegerField(blank=True, null=True)),
                ('total_characters', models.IntegerField(blank=True, null=True)),
                ('total_paragraphs', models.IntegerField(blank=True, null=True)),
                ('total_syllables', models.IntegerField(blank=True, null=True)),
                ('average_word_difficulty', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Readability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('textstat_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('flesch_reading_ease', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('smog_index', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('flesch_kincaid_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('coleman_liau_index', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('automated_readability_index', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('dale_chall_readability_score', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('linsear_write_formula', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('gunning_fog', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Language'),
        ),
    ]
