# Generated by Django 2.2.2 on 2019-06-18 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190618_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_raw_text',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Book'),
        ),
    ]
