# Generated by Django 2.2.2 on 2019-06-20 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190618_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Text',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_text', to='core.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book_stats',
            name='book',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='book_stats', to='core.Book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_readability',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_readability', to='core.Book'),
        ),
        migrations.AlterField(
            model_name='download',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='download',
            name='rating',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Book_Raw_Text',
        ),
    ]
