# Generated by Django 2.2.2 on 2019-06-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190620_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=None, max_length=63),
            preserve_default=False,
        ),
    ]
