# Generated by Django 2.2.2 on 2019-06-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
