# Generated by Django 2.2.2 on 2019-06-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=None, max_length=63),
            preserve_default=False,
        ),
    ]
