# Generated by Django 2.2.3 on 2019-07-22 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190621_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word_Counter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counter', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
